---
abstract: 'Reveal HTML document structure in a myriad of colors'
author:
  - 'Ron Savage <ron@savage.net.au>'
build_requires:
  Test::More: 0
  Test::Pod: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120630'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Revelation
provides:
  HTML::Revelation:
    file: lib/HTML/Revelation.pm
    version: 1.03
requires:
  File::Spec: 0
  HTML::Entities::Interpolate: 0
  HTML::Tagset: 0
  HTML::TreeBuilder: 0
  List::Cycle: 0
  accessors::classic: 0
resources:
  license: http://www.perlfoundation.org/artistic_license_1_0
version: 1.03
